#!/usr/bin/env bash
# Generated by scripts/generate_run_scripts.py. Do not edit directly.
set -euo pipefail

IMAGE_NAME="cpp-course-pohjolainen"

# Build context should be this script's directory to avoid running from elsewhere.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# Check if Docker is insalled
if ! command -v docker >/dev/null 2>&1; then
  echo "❌ Docker not installed or not in PATH."
  exit 1
fi

# Is Docker daemon running
if ! docker info >/dev/null 2>&1; then
  echo "❌ Docker not running, please run Docker."
  exit 1
fi

echo "🔧 Building C++ environment (Docker image: $IMAGE_NAME)"
docker build -t "$IMAGE_NAME" "$SCRIPT_DIR"

# BEGIN SYNC
# This block is the source for run.bat output. Run scripts/sync_run_bat.py after edits.
echo
echo "Starting C++ development environment"
echo "Workspace:"
echo "     $(pwd)"
echo "Compile:"
echo "     clang++ -std=c++20 -Wall -Wextra mycode.cpp -o mycode"
echo "Run:"
echo "     ./mycode"
echo "Edit files (inside the container):"
echo "     nano mycode.cpp"
echo "Exit:"
echo "     exit"
# END SYNC

docker run --rm -it \
  -e TERM=xterm-256color \
  -v "$(pwd)":/workspace \
  "$IMAGE_NAME"
